# Generated by Django 4.2.28 on 2026-07-09 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webgbt', '0020_alter_komentar_options_komentar_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komentar',
            options={'ordering': ['-dibuat_pada']},
        ),
        migrations.AddField(
            model_name='komentar',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='komentar',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
